### ISSUE TITLE
Request to change license

### ISSUE THREAD

**Issue by RonHeck** [EddieEldridge/SHA256-in-C#3]
Dear Mr. Eldridge,

Currently I need to do some small things in plain c and stumbled upon your SHA256 implementation. (I'm a .NET developer, so plain C is a mess for me :D) It works pretty well and I just need to change some small details to make it work for my use case. Unfortunately, I realized a bit too late that you are using a GPL license which is useless for me. Therefore, I would like to ask if it is possible to change it to an MIT license.

Many thanks in advance

Translated with DeepL.com (free version)

**Comment by Medik-GH** [comment]
I've updated the license. Feel free to do whatever you like with it :)
